services:
  leadboardnet:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${DB_CONN}
    ports:
      - "8080:8080"
