# This is a generated file. Not intended for manual editing.
services:
  leadboardnet:
    build:
      context: "C:\\Users\\erick_ortiz\\source\\repos\\LeadBoardNet"
      dockerfile: "LeadBoardNet.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/LeadBoardNet.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "leadboardnet:dev"
    ports: []
    volumes:
    - "C:\\Users\\erick_ortiz\\source\\repos\\LeadBoardNet\\LeadBoardNet.API:/app:rw"
    - "C:\\Users\\erick_ortiz\\source\\repos\\LeadBoardNet:/src:rw"
    - "C:\\Users\\erick_ortiz\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
